<script>
    $('header').css('height', '350px')
</script>
<div class="container">
    <div class="row row-margin-zero about-us-margin">
        <div class="col-md-12 col-padding-zero">
            <h4 class="about-h-style">TERMS AND CONDITIONS</h4>
            <p class="about-psg-style">
                Welcome to Fashion Found. If you continue to browse and use this website you are agreeing to abide with and be bound by the following terms and conditions, which together with our privacy policy govern the relationship of Fashion Found with you in relation to this website. Please read them carefully.
            </p>
            <p class="about-psg-style">
                These Website (“Terms“) are published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011. These Terms are an ‘electronic record’ as contemplated under section 2(t) of the Information Technology Act, 2000 and the Rules thereunder. These Terms being an electronic record are generated by a computer system and do not require any physical or digital signatures.
            </p>

            <h4 class="about-h-style">I. INTRODUCTION</h4>
            <ul class="aboutcontent-ul">
                <li><span>The website www.fashionfound.in ("Website") is operated by Wow Crest, a company incorporated under the Partnership Act, 1932 ("Fashion Found") having its registered office at Pune - 411037. Use of the Website and its services is governed by these Terms of Use (“Terms”).</span></li>
                <li><span>By using the Website, users signify they have carefully read, understood and agree to be bound by these Terms. When users transact or browse through the Website or avail any service provided by the Website, in present or future, users accept and agree to be bound by these Terms, policies, guidelines and conditions of Fashion Found service.</span></li>
                <li><span>These Terms could be changed, altered, edited, amended, modified, reviewed, revised or substituted by Fashion Found at any time with or without prior notice and users are requested to read the Terms before using or accessing the Website.</span></li>
            </ul>

            <h4 class="about-h-style">II. PLATFORM SERVICES</h4>
            <ul class="aboutcontent-ul">
                <li><span>The Website is a platform that users utilize to communicate and transact with one another.</span></li>
                <li><span>Fashion Found is not and cannot be a party to or control in any manner any transaction between users (Costumer, Designer, Boutique) of the Website.</span></li>
                <li><span>The Website is only a platform that can be used by users to reach a larger base and tend to get more leads.</span></li>
                <li><span>Fashion Found is only providing a platform for communication and the contract for sale of the products shall be a strictly bipartite contract between the buyer and the seller.</span></li>
                <li><span>At no time shall Fashion Found hold any right, title or interest over the products or have any obligations or liabilities in respect of such bipartite contract entered into between the buyer and seller.</span></li>
                <li><span>Users may upload and display the images and information of their products offered for booking on the Website’s online platform.</span></li>
                <li><span>These should match to all the guidelines stated by Fashion Found (refer business with us page) so that your profile looks appealing.</span></li>
                <li><span>Provision of a specific service through the online platform of the Website will be subject to users agreeing and consenting to certain additional terms, rules, policies, procedures, guidelines, disclaimers, notices or otherwise, if any, as applicable to such service (“Additional Terms“) and if there is any conflict between the Terms of Use and the Additional Terms, the Additional Terms shall take precedence in relation to that specific service.</span></li>
            </ul>

            <h4 class="about-h-style">COMMUNICATIONS</h4>
            <p class="about-psg-style">When you browse www.fashionfound.in, you are communicating with us electronically. You hereby agree to receive communications from us electronically. We will communicate with you by e-mail. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement.</p>

            <h4 class="about-h-style">PATENT</h4>
            <p class="about-psg-style">All content shown on this site is the property of Fashion Found. Assemblage of all content on this site and all software use on this website is the exclusive property of fashionfound.in</p>
            
            <h4 class="about-h-style">PRODUCTS</h4>
            <ul class="aboutcontent-ul">
                <li><span>FashionFound.in does not provide any warranty or guarantee that the product descriptions or any other contents’ accuracy, timeliness, performance, completeness, reliability or suitability of the information and products found on this website for any particular purpose.</span></li>

                <li><span>FashionFound.in tries the best of its information attempts to be as accurate as possible.</span></li>

                <li><span>FashionFound.in holds no liability for any inaccuracies or errors. It shall be your own responsibility to ensure that products, services or information available through this website meet your specific requirements.</span></li>
            </ul>

            <h4 class="about-h-style">SITE ACCESS</h4>

            <ul class="aboutcontent-ul">
                <li><span>FashionFound.in gives you permission to access and make personal use of this site. Though FashionFound.in does not allows you any commercial use of contents of this site.</span></li>
                <li><span>The content of the pages of this website is for your general information and use only. It is subject to change without notice.</span></li>
            </ul>

            <h4 class="about-h-style">YOU AGREE AND CONFIRM</h4>
            <ul class="aboutcontent-ul">
                <li><span>You agree as you use this website that it is your responsibility to maintain the confidentiality of your account and password. For restriction of access to your computer and for all activities that would arise under your account or password. FashionFound.in reserves the right to decline service, remove or terminate account or cancel orders in sole discretion.</span></li>
                <li><span>That you will use the services provided by FashionFound.in and comply with all applicable law and regulations while using the website and transacting on the website</span></li>
                <li><span>That you will provide validate and accurate information at all instances where such information is requested of you. FashionFound.in reserves the right to confirm and validate the information and other details provided by you at any point of time. If any discrepancies are found in the information provided by you FashionFound.in has the right in its sole discretion to reject the registration and debar you from using the services at FashionFound.in without prior information.</span></li>
                <li><span>That before booking an order or before doing any business with us you will check the terms and conditions of the product carefully.</span></li>
            </ul>
            
            <h4 class="about-h-style">PAYMENTS</h4>
            <p class="about-psg-style">Payments can be made through credit card, debit card and net banking.</p>

            <h4 class="about-h-style">JURISDICTION</h4>
            <p class="about-psg-style">All disputes shall be subject to the jurisdiction of courts in Pune.</p>

            <h4 class="about-h-style">INDEMNITY</h4>
            <p class="about-psg-style">You agree to indemnify and hold harmless FashionFound.in and its associates from and against all claims, liabilities, losses, costs, expenses and damages including attorney’s fees caused by or arising out of claims based upon your actions or inactions from your use of this website.</p>

            <h4 class="about-h-style">TERMINATION</h4>
            <p class="about-psg-style">These terms and conditions are effective unless and until terminated by Fashion Found. Any such termination of the terms and conditions shall not cancel your obligation to pay for the product already ordered from the site or affect any liability that may have arisen hereto.</p>


        </div>
    </div>
</div>